services:
    app:
        build:
            context: .docker/php-fpm
        restart: always
        entrypoint: dockerize -wait tcp://mysql:3306 -timeout 40s ./.docker/entrypoint.sh
        environment:
            - PHP_OPCACHE_VALIDATE_TIMESTAMPS=1
            - DB_HOST=mysql
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
        volumes:
            - '.:/var/www'
        networks:
            - sail
        depends_on:
            - mysql
            - redis

    server:
        build: .docker/nginx
        entrypoint: dockerize -template ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf -wait tcp://app:9000 -timeout 40s nginx -g "daemon off;"
        restart: always
        tty: true
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
        networks:
            - sail
        depends_on:
            - app
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '3307:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    redis:
        image: 'redis:alpine'
        ports:
            - '6379:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
    batch-queue:
        build: .docker/php-workers
        restart: unless-stopped
        working_dir: /var/www
        user: "82:82"
        networks:
            - sail
        entrypoint: php artisan queue:work --timeout=60 --tries=3 --queue=debt-batch-processing
        volumes:
            - .:/var/www
        depends_on:
            - mysql
            - redis
    notification-queue:
        build: .docker/php-workers
        restart: unless-stopped
        working_dir: /var/www
        user: "82:82"
        networks:
            - sail
        entrypoint: php artisan queue:work --timeout=60 --tries=3 --queue=debt-notification-processing
        volumes:
            - .:/var/www
        depends_on:
            - mysql
            - redis
    store-queue:
        build: .docker/php-workers
        restart: unless-stopped
        working_dir: /var/www
        user: "82:82"
        networks:
            - sail
        entrypoint: php artisan queue:work --timeout=60 --tries=3 --queue=debt-store-processing
        volumes:
            - .:/var/www
        depends_on:
            - mysql
            - redis
    cron-notification:
        build: .docker/php-workers
        restart: unless-stopped
        user: "82:82"
        networks:
            - sail
        entrypoint: /usr/local/bin/entrypoint-cronworker
        volumes:
            - .:/var/www
        depends_on:
            - mysql
            - app

networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
    sail-redis:
        driver: local
